"""Design prototypes for website v0: the landing page and the MobileNetV3-Large model page (design only).

Usage:  python web/prototypes/build_prototypes.py [--open]
Needs:  published/labels/*/label.json (committed)
Writes: web/prototypes/out/ (gitignored): index.html, models/mobilenet-v3-large/index.html, assets/, fonts/

Not the site generator: it exists so H can judge the design with real values. Every number comes from the
released labels. Before writing, it checks and prints PASS / FAIL:
- numbers: every number a reader sees (page text and the texts the condition switches show) is a label
  number in one of the labels' own formats (brokkr_edge.label_render.FORMATS), or a meter tick;
- meter: for every condition, the needle angle and the interval band equal the ones recomputed from that
  label's shrinking cost and its interval; every table bar's width equals its top-1;
- themes: web/themes.py's rules (contrast, accent distinct from the INT8 blue, fixed colours untouched);
- build IDs: generated by the rule below, unique across the labels.
--open: open the landing page in the default browser afterwards (works from the file system, no server).
"""

import argparse
import html
import json
import math
import re
import shutil
import subprocess
import sys
import webbrowser
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "web"))

import themes  # noqa: E402  (web/themes.py)

from brokkr_edge.label_render import CAUSE_TITLE, FORMATS, NUMBER, WORDS_WITH_DIGITS, _leaves  # noqa: E402

LABELS = ROOT / "published" / "labels"
WEB = ROOT / "web"
OUT = WEB / "prototypes" / "out"
FEATURED = "mobilenet_v3_large"  # the bench meter's model and the prototype model page
SOURCE_WORDS = {"official": "Brokkr study", "user-submitted": "User-submitted"}  # H, 3 October 2026


def esc(x) -> str:
    return html.escape(str(x))


def f(value, kind: str) -> str:
    return FORMATS[kind](value)


def count(n: int) -> str:
    """A whole number with a thousands separator (10,000)."""
    return f"{n:,}"


def interval(m: dict, kind: str) -> str:
    return f"{f(m['ci95'][0], kind)} to {f(m['ci95'][1], kind)}"


# ---- the label data each page needs ----


def load_labels() -> dict:
    labs = {p.parent.name: json.loads(p.read_text(encoding="utf-8")) for p in LABELS.glob("*/label.json")}
    return dict(sorted(labs.items(), key=lambda kv: kv[1]["model"]["display_name"].lower()))


def builds(label: dict) -> tuple:
    by_role = {b["role"]: b for b in label["builds"]}
    return by_role["reference"], by_role["labelled"]


def measurement(label: dict, metric: str, build: dict, cid: str):
    return next(
        (
            m
            for m in label["measurements"]
            if (m["metric"], m["build_id"], m["condition_id"]) == (metric, build["build_id"], cid)
        ),
        None,
    )


def envelope_row(label: dict, build: dict, cid: str):
    """The envelope row of a build in a damaged condition; None for clean (the reference, not judged)."""
    return next(
        (
            r
            for r in label["envelope"]["rows"]
            if (r["build_id"], r["condition_id"]) == (build["build_id"], cid)
        ),
        None,
    )


def short_condition(label_text: str) -> str:
    """'fog (Brokkr) s3' -> 'fog s3' for a button; the suite is the button group's name."""
    return label_text.replace(" (Brokkr)", "").replace(" (ImageNet-C)", "")


# ---- build IDs and addresses (proposal; docs in the reply to H, 4 October 2026) ----

PART = re.compile(r"[A-Z]+[0-9.]*(?=[A-Z][a-z]|$)|[A-Z]?[a-z]+[0-9.]*|[0-9.]+[A-Za-z]*")


def model_code(display_name: str) -> str:
    """'MobileNetV3-Large' -> 'MNV3L': split at spaces, hyphens and capitals; a plain word gives its first
    letter, a part with digits or in capitals is kept whole (dots dropped)."""
    code = ""
    for word in re.split(r"[\s-]+", display_name):
        for part in PART.findall(word):
            whole = any(c.isdigit() for c in part) or part.isupper()
            code += part.upper().replace(".", "") if whole else part[0].upper()
    return code


def build_slug(build: dict) -> str:
    """'int8' + 'percentile99.99' -> 'int8-percentile-99.99'; FP32 -> 'fp32'."""
    method = (build.get("recipe") or {}).get("method") or ""
    m = re.fullmatch(r"([a-z]+)([0-9.]*)", method)
    parts = [build["precision"], *(p for p in (m.groups() if m else ()) if p)]
    return "-".join(parts)


def build_id(label: dict, build: dict) -> str:
    """'BRK-' + model code + precision + recipe code (first letter of the method, then its digits)."""
    slug = build_slug(build).split("-")
    recipe = (
        (slug[1][0].upper() + (slug[2].replace(".", "") if len(slug) > 2 else "")) if len(slug) > 1 else ""
    )
    return "-".join(
        p for p in ("BRK", model_code(label["model"]["display_name"]), slug[0].upper(), recipe) if p
    )


def model_slug(label: dict) -> str:
    return label["model"]["name"].replace("_", "-")


# ---- the bench meter (geometry shared by the page and its check) ----

CX, CY, R = 160.0, 158.0, 122.0
SWEEP_FROM, SWEEP = 210.0, 240.0  # degrees: the dial runs from lower left, over the top, to lower right


def meter_domain(label: dict) -> tuple:
    ref, lab = builds(label)
    costs = [measurement(label, "shrinking_cost", lab, c["condition_id"]) for c in label["conditions"]]
    lows = [m["ci95"][0] for m in costs if m] + [label["envelope"]["rule"]["large_shrinking_cost_below"]]
    highs = [m["ci95"][1] for m in costs if m] + [0.0]
    return (math.floor(min(lows) / 0.1) * 0.1, max(0.0, math.ceil(max(highs) / 0.05) * 0.05))


def angle(value: float, domain: tuple) -> float:
    lo, hi = domain
    return SWEEP_FROM - (hi - value) / (hi - lo) * SWEEP


def point(a: float, r: float) -> tuple:
    return CX + r * math.cos(math.radians(a)), CY - r * math.sin(math.radians(a))


def arc(v_from: float, v_to: float, domain: tuple, r: float) -> str:
    """An arc path from the higher value to the lower one (clockwise on screen)."""
    a1, a2 = angle(max(v_from, v_to), domain), angle(min(v_from, v_to), domain)
    (x1, y1), (x2, y2) = point(a1, r), point(a2, r)
    return f"M{x1:.2f} {y1:.2f} A{r:.0f} {r:.0f} 0 {1 if a1 - a2 > 180 else 0} 1 {x2:.2f} {y2:.2f}"


def meter_ticks(domain: tuple) -> list:
    lo, hi = domain
    return [round(k * 0.05, 4) for k in range(math.ceil(lo / 0.05 - 1e-9), math.floor(hi / 0.05 + 1e-9) + 1)]


def meter_svg(label: dict, cost: dict, domain: tuple) -> str:
    line = label["envelope"]["rule"]["large_shrinking_cost_below"]
    lo, hi = domain
    parts = [
        f'<path d="{arc(hi, line, domain, R)}" class="zone zone-small"/>',
        f'<path d="{arc(line, lo, domain, R)}" class="zone zone-large"/>',
    ]
    for t in meter_ticks(domain):
        major = abs(round(t * 100) % 10) == 0
        (x1, y1), (x2, y2) = (
            point(angle(t, domain), R - 10),
            point(angle(t, domain), R - (24 if major else 18)),
        )
        parts.append(
            f'<line x1="{x1:.2f}" y1="{y1:.2f}" x2="{x2:.2f}" y2="{y2:.2f}" '
            f'class="tick{" major" if major else ""}"/>'
        )
        if major:
            x, y = point(angle(t, domain), R - 40)
            parts.append(
                f'<text x="{x:.1f}" y="{y + 5:.1f}" class="tick-label" data-tick="{t}">{100 * t:.0f}</text>'
            )
    for v, name, cls in (
        ((hi + line) / 2, "small", "zone-label"),
        ((line + lo) / 2, "large", "zone-label zone-label-large"),
    ):
        x, y = point(angle(v, domain), R + 14)  # outside the arc, anchored away from it
        anchor = "end" if x < CX - 20 else "start" if x > CX + 20 else "middle"
        parts.append(f'<text x="{x:.1f}" y="{y + 4:.1f}" class="{cls}" text-anchor="{anchor}">{name}</text>')
    parts.append(f'<text x="{CX}" y="{CY + 96}" class="dial-unit">INT8 − FP32, points</text>')
    parts.append(
        f'<path d="{arc(cost["ci95"][0], cost["ci95"][1], domain, R - 4)}" class="band" id="meter-band"/>'
    )
    a = angle(cost["value"], domain)
    parts.append(
        f'<g class="needle" id="meter-needle" style="transform: rotate({-a:.3f}deg)" '
        f'data-angle="{a:.3f}" data-rest="{angle(0.0, domain):.3f}">'
        f'<line x1="{CX - 18}" y1="{CY}" x2="{CX + R - 14}" y2="{CY}"/></g>'
    )
    parts.append(
        f'<circle cx="{CX}" cy="{CY}" r="11" class="hub"/>'
        f'<circle cx="{CX}" cy="{CY}" r="3.5" class="hub-dot"/>'
    )
    return (
        '<svg class="meter-dial" viewBox="-36 0 392 316" role="img" aria-labelledby="meter-title">'
        '<title id="meter-title">Shrinking cost on a dial: needle at the measured value, shaded band '
        "for its interval</title>"
        f'<circle cx="{CX}" cy="{CY}" r="{R + 30}" class="bezel"/>' + "".join(parts) + "</svg>"
    )


# ---- shared page parts ----

THEME_BOOT = (
    "<script>(function(){var d=document.documentElement;d.className='js';var ok=%s,t=null;"
    "try{t=new URLSearchParams(location.search).get('theme')||localStorage.getItem('brokkr-theme')}"
    "catch(e){}if(ok.indexOf(t)>=0)d.setAttribute('data-theme',t)})();</script>"
)
ICON = {"not harmful": "✓", "borderline": "◐", "harmful": "⚠", "not tested": "○", "INT8 build failed": "✕"}
KIND = {
    "not harmful": "ok",
    "borderline": "borderline",
    "harmful": "harm",
    "not tested": "untested",
    "INT8 build failed": "failed",
}


def page(title: str, depth: int, body: str, versions: str) -> str:
    up = "../" * depth
    options = "".join(f'<option value="{k}">{esc(t["name"])}</option>' for k, t in themes.THEMES.items())
    return f"""<!doctype html>
<html lang="en" class="no-js">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)}</title>
{THEME_BOOT % json.dumps(list(themes.THEMES))}
<link rel="stylesheet" href="{up}assets/themes.css">
<link rel="stylesheet" href="{up}assets/site.css">
</head>
<body>
<a class="skip" href="#main">Skip to content</a>
<header class="nav">
  <a class="brand" href="{up}index.html"><span class="brand-mark" aria-hidden="true"></span>BROKKR</a>
  <nav aria-label="Main"><a href="{up}index.html">Catalog</a>
    <a href="{up}models/mobilenet-v3-large/index.html">Example model</a></nav>
  <label class="theme-pick js-only">Theme
    <select id="theme-picker"><option value="auto">System</option>{options}</select></label>
</header>
<main id="main">
{body}
</main>
<footer class="foot"><p class="mono">{versions}</p>
<p>Design prototype for website v0. Numbers are read from the released labels in
<span class="mono">published/labels/</span>.</p></footer>
<script src="{up}assets/site.js"></script>
</body>
</html>
"""


def versions_line(labs: dict) -> str:
    gens = {
        (lab["generated"]["by"], lab["generated"]["commit"][:7], lab["schema_version"])
        for lab in labs.values()
    }
    by, commit, schema = sorted(gens)[0]
    site = subprocess.run(
        ["git", "rev-parse", "--short=7", "HEAD"], capture_output=True, text=True, cwd=ROOT
    ).stdout.strip()
    dirty = subprocess.run(
        ["git", "status", "--porcelain"], capture_output=True, text=True, cwd=ROOT
    ).stdout.strip()
    mixed = "" if len(gens) == 1 else " (labels made by different versions)"
    return (
        f"Labels: {esc(by)} at commit {commit}, label schema version {schema}{mixed} · "
        f"pages built at commit {site}{' with uncommitted changes' if dirty else ''}"
    )


def verdict(label: dict, lab: dict, cid: str) -> tuple:
    """(kind, icon, text) of the INT8 build's state in a condition."""
    if lab["status"] == "failed":
        return "failed", ICON["INT8 build failed"], "INT8 build failed"
    row = envelope_row(label, lab, cid)
    if row is None:
        return "untested", "–", "reference condition (not judged)"
    return KIND[row["state"]], ICON[row["state"]], row["state"]


def cost_verdict(label: dict, cost: dict, row) -> tuple:
    """The meter's verdict: the label's own flag (for clean, which has no envelope row, the same rule: the
    whole interval below the line), else which side of the line the whole interval is on."""
    line = label["envelope"]["rule"]["large_shrinking_cost_below"]
    large = "large shrinking cost" in row["shrinking_cost_flags"] if row else cost["ci95"][1] < line
    if large:
        return "harm", "⚠", "Large shrinking cost"
    if cost["ci95"][0] > line:
        return "ok", "✓", "Small shrinking cost"
    return "borderline", "◐", "Too close to the line to call"


# ---- the landing page ----


def pixel_hero(cols: int = 28, rows: int = 9) -> str:
    """Squares cooling from ember (left) to stone (right) in discrete steps: quantization as heat."""
    steps = len(themes.THEMES["ember"]["heat"])
    cells = []
    for r in range(rows):
        for c in range(cols):
            jitter = ((r * 7 + c * 13) % 5 - 2) * 0.35  # a fixed pattern, so the picture never changes
            step = min(steps - 1, max(0, int((c / (cols - 1)) * steps + jitter)))
            size = 13 if step < 3 else 12
            cells.append(
                f'<rect x="{c * 16 + (14 - size) / 2:.1f}" y="{r * 16 + (14 - size) / 2:.1f}" '
                f'width="{size}" height="{size}" rx="1.5" fill="var(--heat-{step})"/>'
            )
    return (
        f'<svg class="hero-pixels" viewBox="0 0 {cols * 16} {rows * 16}" aria-hidden="true" '
        f'focusable="false">{"".join(cells)}</svg>'
    )


def landing(labs: dict, checks: dict) -> str:
    feat = labs[FEATURED]
    ref, lab = builds(feat)
    conditions = feat["conditions"]
    domain = meter_domain(feat)
    clean_cost = measurement(feat, "shrinking_cost", lab, "clean")
    ci_level = f(feat["generated"]["ci_level"], "pct0")
    n_test = next(d["n_items"] for d in feat["datasets"] if d["split"] == "test")

    # Condition switches (radio buttons styled as tactile keys), grouped by suite.
    groups, buttons = {}, []
    for c in conditions:
        groups.setdefault(c["suite"] or "clean", []).append(c)
    for suite, conds in groups.items():
        keys = []
        for c in conds:
            cid = c["condition_id"]
            cost = measurement(feat, "shrinking_cost", lab, cid)
            kind, icon, text = cost_verdict(feat, cost, envelope_row(feat, lab, cid))
            a = angle(cost["value"], domain)
            data = {
                "cost-text": f(cost["value"], "pts"),
                "interval-text": interval(cost, "pts"),
                "verdict": text,
                "verdict-kind": kind,
                "icon": icon,
                "label": c["label"],
                "angle": f"{a:.3f}",
                "band": arc(cost["ci95"][0], cost["ci95"][1], domain, R - 4),
            }
            checks["meter"].append((cid, cost, a, data["band"]))
            attrs = " ".join(f'data-{k}="{esc(v)}"' for k, v in data.items())
            keys.append(
                f'<label class="key"><input type="radio" name="cond" value="{esc(cid)}" {attrs}'
                f"{' checked' if cid == 'clean' else ''}>"
                f"<span>{esc(short_condition(c['label']))}</span></label>"
            )
        legend = {"clean": "No damage", "brokkr": "Brokkr's own damage", "imagenet-c": "ImageNet-C damage"}[
            suite
        ]
        buttons.append(
            f'<div class="key-group"><span class="key-group-name">{legend}</span>{"".join(keys)}</div>'
        )

    kind, icon, text = cost_verdict(feat, clean_cost, envelope_row(feat, lab, "clean"))
    bench = f"""
<section class="bench" id="bench" aria-labelledby="bench-h">
  <div class="bench-head"><p class="kicker mono">ON THE BENCH · SHRINKING COST</p>
    <p class="bench-what">{esc(feat["model"]["display_name"])} · INT8 vs FP32</p></div>
  <h2 id="bench-h" class="visually-hidden">The test bench</h2>
  <div class="bench-grid">
    <div class="meter-face">{meter_svg(feat, clean_cost, domain)}</div>
    <div class="readout" aria-live="polite">
      <p class="readout-label">Measured shrinking cost (points)</p>
      <p class="nixie mono" id="r-cost">{f(clean_cost["value"], "pts")}</p>
      <p class="mono readout-sub">{ci_level} interval
      <span id="r-interval">{interval(clean_cost, "pts")}</span></p>
      <p class="readout-label">Verdict</p>
      <p class="verdict v-{kind}" id="r-verdict"><span aria-hidden="true">{icon}</span>
      <span>{text}</span></p>
      <p class="readout-label">Condition</p>
      <p class="mono" id="r-cond">{esc(conditions[0]["label"])}</p>
    </div>
  </div>
  <fieldset class="keys js-only"><legend>Test condition</legend>{"".join(buttons)}</fieldset>
  <p class="note">INT8 minus FP32 top-1 on the same {count(n_test)} test images; the shaded band is
  its {ci_level} interval. Two zones only: the label's large-cost line is the one threshold the rules
  define. The verdict uses the whole interval, not the needle.</p>
</section>"""

    # Every model under every condition: static tables (all shown without JavaScript; one at a time with it).
    tables = []
    for c in conditions:
        cid = c["condition_id"]
        rows = []
        for name, label in labs.items():
            r, b = builds(label)
            fp32 = measurement(label, "top1", r, cid)
            int8 = measurement(label, "top1", b, cid) if b["status"] != "failed" else None
            cost = measurement(label, "shrinking_cost", b, cid) if int8 else None
            vk, vi, vt = verdict(label, b, cid)
            link = (
                f'<a href="models/{model_slug(label)}/index.html">{esc(label["model"]["display_name"])}</a>'
                if name == FEATURED
                else esc(label["model"]["display_name"])
            )

            def bar(m, cls):
                return (
                    f'<span class="bar"><span class="fill {cls}" '
                    f'style="width:{100 * m["value"]:.2f}%"></span></span>'
                    f'<span class="mono">{f(m["value"], "pct")}</span>'
                )

            flags = (envelope_row(label, b, cid) or {}).get("shrinking_cost_flags", []) if int8 else []
            note = ' <span class="flag">near floor</span>' if "not informative" in flags else ""
            rows.append(
                f'<tr><th scope="row">{link}</th><td>{bar(fp32, "fp32")}</td>'
                + (
                    f'<td>{bar(int8, "int8")}</td><td class="mono">{f(cost["value"], "pts")} '
                    f'<span class="ci">({interval(cost, "pts")})</span>{note}</td>'
                    if int8
                    else '<td class="muted" colspan="2">INT8 build failed: not measured</td>'
                )
                + f'<td class="v-{vk}"><span aria-hidden="true">{vi}</span> {esc(vt)}</td></tr>'
            )
        tables.append(f"""<section class="cond-table" data-cond="{esc(cid)}" aria-labelledby="t-{esc(cid)}">
<h3 id="t-{esc(cid)}">Under {esc(c["label"])}</h3>
<div class="scroll"><table class="data">
<thead><tr><th scope="col">Model</th><th scope="col">FP32 top-1</th><th scope="col">INT8 top-1</th>
<th scope="col">Shrinking cost (points, {ci_level} interval)</th>
<th scope="col">INT8 verdict</th></tr></thead>
<tbody>{"".join(rows)}</tbody></table></div></section>""")

    hero = f"""
<section class="hero">
  {pixel_hero()}
  <div class="hero-text">
    <p class="kicker mono">THE FORGE'S TEST BENCH</p>
    <h1>Shrink AI models for small hardware, and find out honestly what you lost.</h1>
    <p>Brokkr forges the part (shrinks a model to INT8), then measures it on the bench: accuracy,
    uncertainty and speed under fog, darkness, blur, noise and low contrast. Every number on a label
    comes from a checked result file, measured on one laptop CPU with simulated damage.</p>
  </div>
</section>"""
    catalog = f"""
<section class="catalog" aria-labelledby="cat-h">
  <h2 id="cat-h">Every model on the bench</h2>
  <p class="note js-only">Pick a test condition above; the table shows measured FP32 and INT8 top-1
  for every model under it. Nothing is interpolated: only tested conditions exist.</p>
  {"".join(tables)}
</section>"""
    return page("Brokkr · the forge's test bench (prototype)", 0, hero + bench + catalog, versions_line(labs))


# ---- the model page ----


def model_page(labs: dict) -> str:
    label = labs[FEATURED]
    ref, lab = builds(label)
    cond_name = {c["condition_id"]: c["label"] for c in label["conditions"]}
    summary, rule = label["summary"], label["envelope"]["rule"]
    tested = f(summary["tested_conditions"], "int")
    ci_level = f(label["generated"]["ci_level"], "pct0")
    clean_cost = measurement(label, "shrinking_cost", lab, "clean")
    test = next(d for d in label["datasets"] if d["split"] == "test")
    hw = label["hardware"][0]

    def names(ids):
        return ", ".join(esc(cond_name[c]) for c in ids) or "none"

    facts = [
        (
            "Shrinking cost, clean images",
            f'{f(clean_cost["value"], "pts")} <span class="unit">points</span>',
            f"{ci_level} interval {interval(clean_cost, 'pts')}",
            None,
        ),
        (
            "Large shrinking cost",
            f"{f(summary['large_shrinking_cost']['count'], 'int')} of {tested} "
            '<span class="unit">conditions</span>',
            f"whole interval below the {f(rule['large_shrinking_cost_below'], 'pts0')} point line: "
            + names(summary["large_shrinking_cost"]["conditions"]),
            "harm",
        ),
        (
            "Harsh even at full size",
            f"{f(summary['reference_harmful']['count'], 'int')} of {tested} "
            '<span class="unit">conditions</span>',
            "FP32 is harmful there too: " + names(summary["reference_harmful"]["conditions"]),
            None,
        ),
        (
            "Uncertainty signal unreliable",
            f"{f(summary['coverage_failed']['count'], 'int')} of {tested} "
            '<span class="unit">conditions</span>',
            f"coverage below the {f(rule['coverage_min'], 'pct0')} line: "
            + names(summary["coverage_failed"]["conditions"]),
            None,
        ),
    ]
    fact_html = "".join(
        f'<div class="fact"><p class="fact-name">{n}</p>'
        f'<p class="fact-value mono{" v-" + k if k else ""}">{v}</p>'
        f'<p class="fact-note">{note}</p></div>'
        for n, v, note, k in facts
    )

    def chips(ids):
        spans = "".join(f"<span class=chip>{esc(cond_name[c])}</span>" for c in ids)
        return f'<p class="chips">{spans}</p>'

    groups = []
    for state in ("not harmful", "borderline", "harmful", "not tested"):
        lines = [x for x in summary["lines"] if x["state"] == state]
        conds = [c for x in lines for c in x["conditions"]]
        if state == "harmful":
            inner = "".join(
                f'<p class="cause">{esc(CAUSE_TITLE[x["cause"]])}: {f(x["count"], "int")}</p>'
                + chips(x["conditions"])
                for x in lines
            )
        else:
            inner = chips(conds) if conds else '<p class="muted">none</p>'
        title = {
            "not harmful": "Not harmful in our tests",
            "borderline": "Borderline",
            "harmful": "Harmful",
            "not tested": "Not tested",
        }[state]
        # A count only where the label stores it (one line in the group); harmful ones count per cause.
        n_line = lines[0]["count"] if len(lines) == 1 and lines[0]["count"] is not None else None
        count_html = f' <span class="mono count">{f(n_line, "int")}</span>' if n_line is not None else ""
        groups.append(
            f'<div class="group g-{KIND[state]}"><h3><span aria-hidden="true">{ICON[state]}</span> {title}'
            f"{count_html}</h3>{inner}</div>"
        )

    cause_of = {c: x["cause"] for x in summary["lines"] if x["cause"] for c in x["conditions"]}
    rows = []
    for c in label["conditions"]:
        cid = c["condition_id"]
        fp32, int8 = measurement(label, "top1", ref, cid), measurement(label, "top1", lab, cid)
        cost, drop = (
            measurement(label, "shrinking_cost", lab, cid),
            measurement(label, "damage_drop", lab, cid),
        )
        cov, size = measurement(label, "coverage", lab, cid), measurement(label, "mean_set_size", lab, cid)
        row = envelope_row(label, lab, cid) or {"state": None, "shrinking_cost_flags": [], "failed": []}
        flag = (
            ' <span class="v-harm" title="large shrinking cost">⚠ large</span>'
            if "large shrinking cost" in row["shrinking_cost_flags"]
            else ""
        )
        cause = f'<br><span class="muted">{esc(CAUSE_TITLE[cause_of[cid]])}</span>' if cid in cause_of else ""
        failed = (
            f'<br><span class="muted">failed: {esc(", ".join(row["failed"]))}</span>' if row["failed"] else ""
        )
        rows.append(
            f'<tr><th scope="row">{esc(c["label"])}</th><td class="mono">{f(fp32["value"], "pct")}</td>'
            f'<td class="mono">{f(int8["value"], "pct")}</td>'
            f'<td class="mono">{f(cost["value"], "pts")} '
            f'<span class="ci">({interval(cost, "pts")})</span>{flag}</td>'
            + (
                f'<td class="mono">{f(drop["value"], "pts")} '
                f'<span class="ci">({interval(drop, "pts")})</span></td>'
                if drop
                else '<td class="muted">reference</td>'
            )
            + f'<td class="mono">{f(cov["value"], "pct")} · {f(size["value"], "size")}</td>'
            + (
                f'<td class="v-{KIND[row["state"]]}"><span aria-hidden="true">{ICON[row["state"]]}</span> '
                f"{esc(row['state'])}{cause}{failed}</td></tr>"
                if row["state"]
                else '<td class="muted">reference condition</td></tr>'
            )
        )

    address = f"/models/{model_slug(label)}/{build_slug(lab)}/"
    limits = " ".join([esc(x) for x in label["limits"] if not x.startswith("Measured on one machine")][:2])
    body = f"""
<article class="sheet-page">
  <p class="crumbs"><a href="../../index.html">Catalog</a> / {esc(label["model"]["display_name"])}</p>
  <header class="model-head">
    <h1>{esc(label["model"]["display_name"])}</h1>
    <p class="model-sub">{esc(lab["display_name"])}, compared with {esc(ref["display_name"])}</p>
    <p class="ids"><span class="build-id mono"
      title="Brokkr build ID, generated from the build's address">{build_id(label, lab)}</span>
      <span class="mono addr">{esc(address)}</span>
      <span class="source">{SOURCE_WORDS[label["source"]["kind"]]}</span></p>
  </header>
  <section class="facts" aria-label="Key facts">{fact_html}</section>
  <section aria-labelledby="env-h"><h2 id="env-h">Where the INT8 build holds up</h2>
    <p class="note">Each of the {tested} tested conditions, grouped by the INT8 build's own state;
    harmful ones by cause. Lines: damage drop and coverage, as fixed in the label rules.</p>
    <div class="groups">{"".join(groups)}</div></section>
  <section aria-labelledby="dmg-h"><h2 id="dmg-h">Damage table</h2>
    <div class="sheet scroll"><table class="data sheet-table">
      <thead><tr><th scope="col">Condition</th><th scope="col">FP32 top-1</th><th scope="col">INT8 top-1</th>
      <th scope="col">Shrinking cost (points, {ci_level} interval)</th>
      <th scope="col">INT8 damage drop (points)</th>
      <th scope="col">INT8 coverage · set size</th><th scope="col">INT8 state</th></tr></thead>
      <tbody>{"".join(rows)}</tbody></table></div></section>
  <section class="footnote" aria-label="Test conditions">
    <p><strong>Test conditions.</strong> {esc(test["name"])}, {esc(test["split"])} split,
    {count(test["n_items"])} images per condition; {esc(hw["cpu_model"])}, {esc(hw["os"])}. {limits}</p>
  </section>
</article>"""
    return page(f"{label['model']['display_name']} · Brokkr (prototype)", 2, body, versions_line(labs))


# ---- checks ----


def visible_numbers(page_html: str) -> list:
    """Every number a reader can see: page text, hover titles, and the data-*-text the switches show."""
    shown = re.findall(r'data-(?:cost-text|interval-text|verdict|label)="([^"]*)"', page_html)
    shown += re.findall(r'title="([^"]*)"', page_html)
    text = re.sub(r"<(script|style|svg)\b.*?</\1>", " ", page_html, flags=re.S)
    svg_text = re.findall(r"<text[^>]*>([^<]*)</text>", page_html)
    text = html.unescape(re.sub(r"<[^>]+>", " ", text))
    return [text, *map(html.unescape, shown), *svg_text]


def check_numbers(pages: dict, labs: dict, domain: tuple, site_commit: str) -> list:
    strings = {s for lab in labs.values() for s in _leaves(lab) if isinstance(s, str) and re.search(r"\d", s)}
    strings |= {s[:7] for s in strings if re.fullmatch(r"[0-9a-f]{40}", s)} | {site_commit}
    strings |= {build_id(lab, builds(lab)[1]) for lab in labs.values()}
    strings |= {f"/models/{model_slug(lab)}/{build_slug(builds(lab)[1])}/" for lab in labs.values()}
    numbers = [
        v
        for lab in labs.values()
        for v in _leaves(lab)
        if isinstance(v, (int, float)) and not isinstance(v, bool)
    ]
    allowed = set()
    for v in numbers:
        for kind, fn in FORMATS.items():
            if kind != "int" or float(v).is_integer():
                allowed |= set(NUMBER.findall(fn(v)))
        if isinstance(v, int):
            allowed |= set(NUMBER.findall(count(v)))
    allowed |= {f"{100 * t:.0f}" for t in meter_ticks(domain)}
    problems = []
    for name, text in pages.items():
        for chunk in visible_numbers(text):
            for s in sorted(strings, key=len, reverse=True) + list(WORDS_WITH_DIGITS) + ["v0", "ImageNet-C"]:
                chunk = chunk.replace(s, " ")
            loose = [t for t in NUMBER.findall(chunk) if t not in allowed]
            if loose:
                problems.append(f"{name}: numbers not in the labels: {sorted(set(loose))[:8]}")
    return problems


def check_meter(checks: dict, labs: dict, domain: tuple) -> list:
    """Re-read the featured label from disk and recompute every needle angle and band."""
    fresh = json.loads((LABELS / FEATURED / "label.json").read_text(encoding="utf-8"))
    ref, lab = builds(fresh)
    problems = []
    for cid, cost, a, band in checks["meter"]:
        m = measurement(fresh, "shrinking_cost", lab, cid)
        if (m["value"], m["ci95"]) != (cost["value"], cost["ci95"]):
            problems.append(f"meter {cid}: value differs from the label")
        if abs(angle(m["value"], domain) - a) > 0.5:
            problems.append(
                f"meter {cid}: needle at {a:.2f} degrees, the value says {angle(m['value'], domain):.2f}"
            )
        if band != arc(m["ci95"][0], m["ci95"][1], domain, R - 4):
            problems.append(f"meter {cid}: interval band does not match the label's interval")
    bars = re.findall(
        r'style="width:([0-9.]+)%"></span></span><span class="mono">([0-9.]+)%</span>', checks["page"]
    )
    for width, printed in bars:  # each bar's length must equal the number printed beside it
        if abs(float(width) - float(printed)) > 0.005:
            problems.append(f"bar width {width}% differs from its printed top-1 {printed}%")
    if not bars:
        problems.append("no table bars found")
    return problems


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--open", action="store_true")
    args = parser.parse_args()
    labs = load_labels()
    checks = {"meter": []}
    pages = {"index.html": landing(labs, checks), "models/mobilenet-v3-large/index.html": model_page(labs)}
    checks["page"] = pages["index.html"]
    domain = meter_domain(labs[FEATURED])
    site_commit = subprocess.run(
        ["git", "rev-parse", "--short=7", "HEAD"], capture_output=True, text=True, cwd=ROOT
    ).stdout.strip()
    ids = [build_id(lab, builds(lab)[1]) for lab in labs.values()]
    results = [
        ("numbers come from the labels", check_numbers(pages, labs, domain, site_commit)),
        ("meter needle, band and bars match the labels", check_meter(checks, labs, domain)),
        ("theme rules (contrast, accent vs INT8 blue, fixed colours)", themes.check()),
        ("build IDs unique", [] if len(set(ids)) == len(ids) else [f"duplicate build IDs: {ids}"]),
    ]
    ok = True
    for what, problems in results:
        ok &= not problems
        print(f"{'PASS' if not problems else 'FAIL'}: {what}")
        for p in problems[:10]:
            print(f"     {p}")
    if not ok:
        sys.exit(1)
    if OUT.exists():
        shutil.rmtree(OUT)
    for rel, text in pages.items():
        (OUT / rel).parent.mkdir(parents=True, exist_ok=True)
        (OUT / rel).write_text(text, encoding="utf-8", newline="\n")
    (OUT / "assets").mkdir()
    (OUT / "assets" / "themes.css").write_text(themes.css(), encoding="utf-8", newline="\n")
    for name in ("site.css", "site.js"):
        shutil.copy(WEB / "assets" / name, OUT / "assets" / name)
    shutil.copytree(WEB / "fonts", OUT / "fonts")
    print(f"wrote {len(pages)} pages to {OUT.relative_to(ROOT).as_posix()}/; build IDs: {', '.join(ids)}")
    if args.open:
        webbrowser.open((OUT / "index.html").as_uri())


if __name__ == "__main__":
    main()
