"""Design prototypes for website v0: the landing page and the MobileNetV3-Large model page (design only).

Usage:  python web/prototypes/build_prototypes.py [--open]
Needs:  published/labels/*/label.json (committed)
Writes: web/prototypes/out/ (gitignored): index.html, models/mobilenet-v3-large/index.html, assets/, fonts/

Not the site generator (scripts/49_build_site.py; it shares the label lookups, the meter and the hero
picture with it): it exists so H can judge the design with real values. Every number comes from the
released labels. Before writing, it checks and prints PASS / FAIL:
- numbers: every number a reader sees (page text and the texts the condition switches show) is a label
  number in one of the labels' own formats (brokkr_edge.label_render.FORMATS), or a meter tick;
- meter: for every condition, the needle angle and the interval band equal the ones recomputed from that
  label's shrinking cost and its interval; every table bar's width equals its top-1;
- themes: web/themes.py's rules (contrast, accent distinct from the INT8 blue, fixed colours untouched);
- build IDs: generated by the rule in web/site_labels.py, unique across the labels.
--open: open the landing page in the default browser afterwards (works from the file system, no server).
"""

import argparse
import html
import json
import re
import shutil
import subprocess
import sys
import webbrowser
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "web"))

import site_meter as M  # noqa: E402  (web/site_meter.py: the bench meter, shared with the site)
import themes  # noqa: E402  (web/themes.py)
from site_labels import (  # noqa: E402  (web/site_labels.py: label lookups and build IDs, shared)
    SOURCE_WORDS,
    build_id,
    build_slug,
    builds,
    envelope_row,
    load_labels,
    measurement,
    model_slug,
)
from site_meter import R, angle, arc  # noqa: E402
from site_pages import pixel_hero, short_condition  # noqa: E402  (shared with the site)

from brokkr_edge.label_render import CAUSE_TITLE, FORMATS, NUMBER, WORDS_WITH_DIGITS, _leaves  # noqa: E402

LABELS = ROOT / "published" / "labels"
WEB = ROOT / "web"
OUT = WEB / "prototypes" / "out"
FEATURED = "mobilenet_v3_large"  # the bench meter's model and the prototype model page


def esc(x) -> str:
    return html.escape(str(x))


def f(value, kind: str) -> str:
    return FORMATS[kind](value)


def count(n: int) -> str:
    """A whole number with a thousands separator (10,000)."""
    return f"{n:,}"


def interval(m: dict, kind: str) -> str:
    return f"{f(m['ci95'][0], kind)} to {f(m['ci95'][1], kind)}"


# ---- the label data each page needs ----


def meter_domain(label: dict) -> tuple:
    """The prototype's dial covers every condition on the label (the site's covers its four)."""
    return M.domain(label, [c["condition_id"] for c in label["conditions"]])


# ---- shared page parts ----

THEME_BOOT = (
    "<script>(function(){var d=document.documentElement;d.className='js';var ok=%s,t=null;"
    "try{t=new URLSearchParams(location.search).get('theme')||localStorage.getItem('brokkr-theme')}"
    "catch(e){}if(ok.indexOf(t)>=0)d.setAttribute('data-theme',t)})();</script>"
)
ICON = {"not harmful": "✓", "borderline": "◐", "harmful": "⚠", "not tested": "○", "INT8 build failed": "✕"}
KIND = {
    "not harmful": "ok",
    "borderline": "borderline",
    "harmful": "harm",
    "not tested": "untested",
    "INT8 build failed": "failed",
}


def page(title: str, depth: int, body: str, versions: str) -> str:
    up = "../" * depth
    options = "".join(f'<option value="{k}">{esc(t["name"])}</option>' for k, t in themes.THEMES.items())
    return f"""<!doctype html>
<html lang="en" class="no-js">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)}</title>
{THEME_BOOT % json.dumps(list(themes.THEMES))}
<link rel="stylesheet" href="{up}assets/themes.css">
<link rel="stylesheet" href="{up}assets/site.css">
</head>
<body>
<a class="skip" href="#main">Skip to content</a>
<header class="nav">
  <a class="brand" href="{up}index.html"><span class="brand-mark" aria-hidden="true"></span>BROKKR</a>
  <nav aria-label="Main"><a href="{up}index.html">Catalog</a>
    <a href="{up}models/mobilenet-v3-large/index.html">Example model</a></nav>
  <label class="theme-pick js-only">Theme
    <select id="theme-picker"><option value="auto">System</option>{options}</select></label>
</header>
<main id="main">
{body}
</main>
<footer class="foot"><p class="mono">{versions}</p>
<p>Design prototype for website v0. Numbers are read from the released labels in
<span class="mono">published/labels/</span>.</p></footer>
<script src="{up}assets/site.js"></script>
</body>
</html>
"""


def versions_line(labs: dict) -> str:
    gens = {
        (lab["generated"]["by"], lab["generated"]["commit"][:7], lab["schema_version"])
        for lab in labs.values()
    }
    by, commit, schema = sorted(gens)[0]
    site = subprocess.run(
        ["git", "rev-parse", "--short=7", "HEAD"], capture_output=True, text=True, cwd=ROOT
    ).stdout.strip()
    dirty = subprocess.run(
        ["git", "status", "--porcelain"], capture_output=True, text=True, cwd=ROOT
    ).stdout.strip()
    mixed = "" if len(gens) == 1 else " (labels made by different versions)"
    return (
        f"Labels: {esc(by)} at commit {commit}, label schema version {schema}{mixed} · "
        f"pages built at commit {site}{' with uncommitted changes' if dirty else ''}"
    )


def verdict(label: dict, lab: dict, cid: str) -> tuple:
    """(kind, icon, text) of the INT8 build's state in a condition."""
    if lab["status"] == "failed":
        return "failed", ICON["INT8 build failed"], "INT8 build failed"
    row = envelope_row(label, lab, cid)
    if row is None:
        return "untested", "–", "reference condition (not judged)"
    return KIND[row["state"]], ICON[row["state"]], row["state"]


# ---- the landing page ----


def landing(labs: dict, checks: dict) -> str:
    feat = labs[FEATURED]
    ref, lab = builds(feat)
    conditions = feat["conditions"]
    domain = meter_domain(feat)
    clean_cost = measurement(feat, "shrinking_cost", lab, "clean")
    ci_level = f(feat["generated"]["ci_level"], "pct0")
    n_test = next(d["n_items"] for d in feat["datasets"] if d["split"] == "test")

    # Condition switches (radio buttons styled as tactile keys), grouped by suite.
    groups, buttons = {}, []
    for c in conditions:
        groups.setdefault(c["suite"] or "clean", []).append(c)
    for suite, conds in groups.items():
        keys = []
        for c in conds:
            cid = c["condition_id"]
            cost = measurement(feat, "shrinking_cost", lab, cid)
            kind, icon, text = M.verdict(feat, cost, cid)
            a = angle(cost["value"], domain)
            data = {
                "cost-text": f(cost["value"], "pts"),
                "interval-text": interval(cost, "pts"),
                "verdict": text,
                "verdict-kind": kind,
                "icon": icon,
                "label": c["label"],
                "angle": f"{a:.3f}",
                "band": arc(cost["ci95"][0], cost["ci95"][1], domain, R - 4),
            }
            checks["meter"].append((cid, cost, a, data["band"]))
            attrs = " ".join(f'data-{k}="{esc(v)}"' for k, v in data.items())
            keys.append(
                f'<label class="key"><input type="radio" name="cond" value="{esc(cid)}" {attrs}'
                f"{' checked' if cid == 'clean' else ''}>"
                f"<span>{esc(short_condition(c['label']))}</span></label>"
            )
        legend = {"clean": "No damage", "brokkr": "Brokkr's own damage", "imagenet-c": "ImageNet-C damage"}[
            suite
        ]
        buttons.append(
            f'<div class="key-group"><span class="key-group-name">{legend}</span>{"".join(keys)}</div>'
        )

    kind, icon, text = M.verdict(feat, clean_cost, "clean")
    bench = f"""
<section class="bench" id="bench" aria-labelledby="bench-h">
  <div class="bench-head"><p class="kicker mono">ON THE BENCH · SHRINKING COST</p>
    <p class="bench-what">{esc(feat["model"]["display_name"])} · INT8 vs FP32</p></div>
  <h2 id="bench-h" class="visually-hidden">The test bench</h2>
  <div class="bench-grid">
    <div class="meter-face">{M.svg(feat, clean_cost, domain)}</div>
    <div class="readout" aria-live="polite">
      <p class="readout-label">Measured shrinking cost (points)</p>
      <p class="nixie mono" id="r-cost">{f(clean_cost["value"], "pts")}</p>
      <p class="mono readout-sub">{ci_level} interval
      <span id="r-interval">{interval(clean_cost, "pts")}</span></p>
      <p class="readout-label">Verdict</p>
      <p class="verdict v-{kind}" id="r-verdict"><span aria-hidden="true">{icon}</span>
      <span>{text}</span></p>
      <p class="readout-label">Condition</p>
      <p class="mono" id="r-cond">{esc(conditions[0]["label"])}</p>
    </div>
  </div>
  <fieldset class="keys js-only"><legend>Test condition</legend>{"".join(buttons)}</fieldset>
  <p class="note">INT8 minus FP32 top-1 on the same {count(n_test)} test images; the shaded band is
  its {ci_level} interval. Two zones only: the label's large-cost line is the one threshold the rules
  define. The verdict uses the whole interval, not the needle.</p>
</section>"""

    # Every model under every condition: static tables (all shown without JavaScript; one at a time with it).
    tables = []
    for c in conditions:
        cid = c["condition_id"]
        rows = []
        for name, label in labs.items():
            r, b = builds(label)
            fp32 = measurement(label, "top1", r, cid)
            int8 = measurement(label, "top1", b, cid) if b["status"] != "failed" else None
            cost = measurement(label, "shrinking_cost", b, cid) if int8 else None
            vk, vi, vt = verdict(label, b, cid)
            link = (
                f'<a href="models/{model_slug(label)}/index.html">{esc(label["model"]["display_name"])}</a>'
                if name == FEATURED
                else esc(label["model"]["display_name"])
            )

            def bar(m, cls):
                return (
                    f'<span class="bar"><span class="fill {cls}" '
                    f'style="width:{100 * m["value"]:.2f}%"></span></span>'
                    f'<span class="mono">{f(m["value"], "pct")}</span>'
                )

            flags = (envelope_row(label, b, cid) or {}).get("shrinking_cost_flags", []) if int8 else []
            note = ' <span class="flag">near floor</span>' if "not informative" in flags else ""
            rows.append(
                f'<tr><th scope="row">{link}</th><td>{bar(fp32, "fp32")}</td>'
                + (
                    f'<td>{bar(int8, "int8")}</td><td class="mono">{f(cost["value"], "pts")} '
                    f'<span class="ci">({interval(cost, "pts")})</span>{note}</td>'
                    if int8
                    else '<td class="muted" colspan="2">INT8 build failed: not measured</td>'
                )
                + f'<td class="v-{vk}"><span aria-hidden="true">{vi}</span> {esc(vt)}</td></tr>'
            )
        tables.append(f"""<section class="cond-table" data-cond="{esc(cid)}" aria-labelledby="t-{esc(cid)}">
<h3 id="t-{esc(cid)}">Under {esc(c["label"])}</h3>
<div class="scroll"><table class="data">
<thead><tr><th scope="col">Model</th><th scope="col">FP32 top-1</th><th scope="col">INT8 top-1</th>
<th scope="col">Shrinking cost (points, {ci_level} interval)</th>
<th scope="col">INT8 verdict</th></tr></thead>
<tbody>{"".join(rows)}</tbody></table></div></section>""")

    hero = f"""
<section class="hero">
  {pixel_hero()}
  <div class="hero-text">
    <p class="kicker mono">THE FORGE'S TEST BENCH</p>
    <h1>Shrink AI models for small hardware, and measure what you lost.</h1>
    <p>Brokkr forges the part (shrinks a model to INT8), then measures it on the bench: accuracy,
    uncertainty and speed under fog, darkness, blur, noise and low contrast. Every number on a label
    comes from a checked result file, measured on one laptop CPU with simulated damage.</p>
  </div>
</section>"""
    catalog = f"""
<section class="catalog" aria-labelledby="cat-h">
  <h2 id="cat-h">Every model on the bench</h2>
  <p class="note js-only">Pick a test condition above; the table shows measured FP32 and INT8 top-1
  for every model under it. Nothing is interpolated: only tested conditions exist.</p>
  {"".join(tables)}
</section>"""
    return page("Brokkr · the forge's test bench (prototype)", 0, hero + bench + catalog, versions_line(labs))


# ---- the model page ----


def model_page(labs: dict) -> str:
    label = labs[FEATURED]
    ref, lab = builds(label)
    cond_name = {c["condition_id"]: c["label"] for c in label["conditions"]}
    summary, rule = label["summary"], label["envelope"]["rule"]
    tested = f(summary["tested_conditions"], "int")
    ci_level = f(label["generated"]["ci_level"], "pct0")
    clean_cost = measurement(label, "shrinking_cost", lab, "clean")
    test = next(d for d in label["datasets"] if d["split"] == "test")
    hw = label["hardware"][0]

    def names(ids):
        return ", ".join(esc(cond_name[c]) for c in ids) or "none"

    facts = [
        (
            "Shrinking cost, clean images",
            f'{f(clean_cost["value"], "pts")} <span class="unit">points</span>',
            f"{ci_level} interval {interval(clean_cost, 'pts')}",
            None,
        ),
        (
            "Large shrinking cost",
            f"{f(summary['large_shrinking_cost']['count'], 'int')} of {tested} "
            '<span class="unit">conditions</span>',
            f"whole interval below the {f(rule['large_shrinking_cost_below'], 'pts0')} point line: "
            + names(summary["large_shrinking_cost"]["conditions"]),
            "harm",
        ),
        (
            "Harsh even at full size",
            f"{f(summary['reference_harmful']['count'], 'int')} of {tested} "
            '<span class="unit">conditions</span>',
            "FP32 is harmful there too: " + names(summary["reference_harmful"]["conditions"]),
            None,
        ),
        (
            "Uncertainty signal unreliable",
            f"{f(summary['coverage_failed']['count'], 'int')} of {tested} "
            '<span class="unit">conditions</span>',
            f"coverage below the {f(rule['coverage_min'], 'pct0')} line: "
            + names(summary["coverage_failed"]["conditions"]),
            None,
        ),
    ]
    fact_html = "".join(
        f'<div class="fact"><p class="fact-name">{n}</p>'
        f'<p class="fact-value mono{" v-" + k if k else ""}">{v}</p>'
        f'<p class="fact-note">{note}</p></div>'
        for n, v, note, k in facts
    )

    def chips(ids):
        spans = "".join(f"<span class=chip>{esc(cond_name[c])}</span>" for c in ids)
        return f'<p class="chips">{spans}</p>'

    groups = []
    for state in ("not harmful", "borderline", "harmful", "not tested"):
        lines = [x for x in summary["lines"] if x["state"] == state]
        conds = [c for x in lines for c in x["conditions"]]
        if state == "harmful":
            inner = "".join(
                f'<p class="cause">{esc(CAUSE_TITLE[x["cause"]])}: {f(x["count"], "int")}</p>'
                + chips(x["conditions"])
                for x in lines
            )
        else:
            inner = chips(conds) if conds else '<p class="muted">none</p>'
        title = {
            "not harmful": "Not harmful in our tests",
            "borderline": "Borderline",
            "harmful": "Harmful",
            "not tested": "Not tested",
        }[state]
        # A count only where the label stores it (one line in the group); harmful ones count per cause.
        n_line = lines[0]["count"] if len(lines) == 1 and lines[0]["count"] is not None else None
        count_html = f' <span class="mono count">{f(n_line, "int")}</span>' if n_line is not None else ""
        groups.append(
            f'<div class="group g-{KIND[state]}"><h3><span aria-hidden="true">{ICON[state]}</span> {title}'
            f"{count_html}</h3>{inner}</div>"
        )

    cause_of = {c: x["cause"] for x in summary["lines"] if x["cause"] for c in x["conditions"]}
    rows = []
    for c in label["conditions"]:
        cid = c["condition_id"]
        fp32, int8 = measurement(label, "top1", ref, cid), measurement(label, "top1", lab, cid)
        cost, drop = (
            measurement(label, "shrinking_cost", lab, cid),
            measurement(label, "damage_drop", lab, cid),
        )
        cov, size = measurement(label, "coverage", lab, cid), measurement(label, "mean_set_size", lab, cid)
        row = envelope_row(label, lab, cid) or {"state": None, "shrinking_cost_flags": [], "failed": []}
        flag = (
            ' <span class="v-harm" title="large shrinking cost">⚠ large</span>'
            if "large shrinking cost" in row["shrinking_cost_flags"]
            else ""
        )
        cause = f'<br><span class="muted">{esc(CAUSE_TITLE[cause_of[cid]])}</span>' if cid in cause_of else ""
        failed = (
            f'<br><span class="muted">failed: {esc(", ".join(row["failed"]))}</span>' if row["failed"] else ""
        )
        rows.append(
            f'<tr><th scope="row">{esc(c["label"])}</th><td class="mono">{f(fp32["value"], "pct")}</td>'
            f'<td class="mono">{f(int8["value"], "pct")}</td>'
            f'<td class="mono">{f(cost["value"], "pts")} '
            f'<span class="ci">({interval(cost, "pts")})</span>{flag}</td>'
            + (
                f'<td class="mono">{f(drop["value"], "pts")} '
                f'<span class="ci">({interval(drop, "pts")})</span></td>'
                if drop
                else '<td class="muted">reference</td>'
            )
            + f'<td class="mono">{f(cov["value"], "pct")} · {f(size["value"], "size")}</td>'
            + (
                f'<td class="v-{KIND[row["state"]]}"><span aria-hidden="true">{ICON[row["state"]]}</span> '
                f"{esc(row['state'])}{cause}{failed}</td></tr>"
                if row["state"]
                else '<td class="muted">reference condition</td></tr>'
            )
        )

    address = f"/models/{model_slug(label)}/{build_slug(lab)}/"
    limits = " ".join([esc(x) for x in label["limits"] if not x.startswith("Measured on one machine")][:2])
    body = f"""
<article class="sheet-page">
  <p class="crumbs"><a href="../../index.html">Catalog</a> / {esc(label["model"]["display_name"])}</p>
  <header class="model-head">
    <h1>{esc(label["model"]["display_name"])}</h1>
    <p class="model-sub">{esc(lab["display_name"])}, compared with {esc(ref["display_name"])}</p>
    <p class="ids"><span class="build-id mono"
      title="Brokkr build ID, generated from the build's address">{build_id(label, lab)}</span>
      <span class="mono addr">{esc(address)}</span>
      <span class="source">{SOURCE_WORDS[label["source"]["kind"]]}</span></p>
  </header>
  <section class="facts" aria-label="Key facts">{fact_html}</section>
  <section aria-labelledby="env-h"><h2 id="env-h">Where the INT8 build holds up</h2>
    <p class="note">Each of the {tested} tested conditions, grouped by the INT8 build's own state;
    harmful ones by cause. Lines: damage drop and coverage, as fixed in the label rules.</p>
    <div class="groups">{"".join(groups)}</div></section>
  <section aria-labelledby="dmg-h"><h2 id="dmg-h">Damage table</h2>
    <div class="sheet scroll"><table class="data sheet-table">
      <thead><tr><th scope="col">Condition</th><th scope="col">FP32 top-1</th><th scope="col">INT8 top-1</th>
      <th scope="col">Shrinking cost (points, {ci_level} interval)</th>
      <th scope="col">INT8 damage drop (points)</th>
      <th scope="col">INT8 coverage · set size</th><th scope="col">INT8 state</th></tr></thead>
      <tbody>{"".join(rows)}</tbody></table></div></section>
  <section class="footnote" aria-label="Test conditions">
    <p><strong>Test conditions.</strong> {esc(test["name"])}, {esc(test["split"])} split,
    {count(test["n_items"])} images per condition; {esc(hw["cpu_model"])}, {esc(hw["os"])}. {limits}</p>
  </section>
</article>"""
    return page(f"{label['model']['display_name']} · Brokkr (prototype)", 2, body, versions_line(labs))


# ---- checks ----


def visible_numbers(page_html: str) -> list:
    """Every number a reader can see: page text, hover titles, and the data-*-text the switches show."""
    shown = re.findall(r'data-(?:cost-text|interval-text|verdict|label)="([^"]*)"', page_html)
    shown += re.findall(r'title="([^"]*)"', page_html)
    text = re.sub(r"<(script|style|svg)\b.*?</\1>", " ", page_html, flags=re.S)
    svg_text = re.findall(r"<text[^>]*>([^<]*)</text>", page_html)
    text = html.unescape(re.sub(r"<[^>]+>", " ", text))
    return [text, *map(html.unescape, shown), *svg_text]


def check_numbers(pages: dict, labs: dict, domain: tuple, site_commit: str) -> list:
    strings = {s for lab in labs.values() for s in _leaves(lab) if isinstance(s, str) and re.search(r"\d", s)}
    strings |= {s[:7] for s in strings if re.fullmatch(r"[0-9a-f]{40}", s)} | {site_commit}
    strings |= {build_id(lab, builds(lab)[1]) for lab in labs.values()}
    strings |= {f"/models/{model_slug(lab)}/{build_slug(builds(lab)[1])}/" for lab in labs.values()}
    numbers = [
        v
        for lab in labs.values()
        for v in _leaves(lab)
        if isinstance(v, (int, float)) and not isinstance(v, bool)
    ]
    allowed = set()
    for v in numbers:
        for kind, fn in FORMATS.items():
            if kind != "int" or float(v).is_integer():
                allowed |= set(NUMBER.findall(fn(v)))
        if isinstance(v, int):
            allowed |= set(NUMBER.findall(count(v)))
    allowed |= {f"{100 * t:.0f}" for t in M.ticks(domain)}
    problems = []
    for name, text in pages.items():
        for chunk in visible_numbers(text):
            for s in sorted(strings, key=len, reverse=True) + list(WORDS_WITH_DIGITS) + ["v0", "ImageNet-C"]:
                chunk = chunk.replace(s, " ")
            loose = [t for t in NUMBER.findall(chunk) if t not in allowed]
            if loose:
                problems.append(f"{name}: numbers not in the labels: {sorted(set(loose))[:8]}")
    return problems


def check_meter(checks: dict, labs: dict, domain: tuple) -> list:
    """Re-read the featured label from disk and recompute every needle angle and band."""
    fresh = json.loads((LABELS / FEATURED / "label.json").read_text(encoding="utf-8"))
    ref, lab = builds(fresh)
    problems = []
    for cid, cost, a, band in checks["meter"]:
        m = measurement(fresh, "shrinking_cost", lab, cid)
        if (m["value"], m["ci95"]) != (cost["value"], cost["ci95"]):
            problems.append(f"meter {cid}: value differs from the label")
        if abs(angle(m["value"], domain) - a) > 0.5:
            problems.append(
                f"meter {cid}: needle at {a:.2f} degrees, the value says {angle(m['value'], domain):.2f}"
            )
        if band != arc(m["ci95"][0], m["ci95"][1], domain, R - 4):
            problems.append(f"meter {cid}: interval band does not match the label's interval")
    bars = re.findall(
        r'style="width:([0-9.]+)%"></span></span><span class="mono">([0-9.]+)%</span>', checks["page"]
    )
    for width, printed in bars:  # each bar's length must equal the number printed beside it
        if abs(float(width) - float(printed)) > 0.005:
            problems.append(f"bar width {width}% differs from its printed top-1 {printed}%")
    if not bars:
        problems.append("no table bars found")
    return problems


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--open", action="store_true")
    args = parser.parse_args()
    labs = load_labels()
    checks = {"meter": []}
    pages = {"index.html": landing(labs, checks), "models/mobilenet-v3-large/index.html": model_page(labs)}
    checks["page"] = pages["index.html"]
    domain = meter_domain(labs[FEATURED])
    site_commit = subprocess.run(
        ["git", "rev-parse", "--short=7", "HEAD"], capture_output=True, text=True, cwd=ROOT
    ).stdout.strip()
    ids = [build_id(lab, builds(lab)[1]) for lab in labs.values()]
    results = [
        ("numbers come from the labels", check_numbers(pages, labs, domain, site_commit)),
        ("meter needle, band and bars match the labels", check_meter(checks, labs, domain)),
        ("theme rules (contrast, accent vs INT8 blue, fixed colours)", themes.check()),
        ("build IDs unique", [] if len(set(ids)) == len(ids) else [f"duplicate build IDs: {ids}"]),
    ]
    ok = True
    for what, problems in results:
        ok &= not problems
        print(f"{'PASS' if not problems else 'FAIL'}: {what}")
        for p in problems[:10]:
            print(f"     {p}")
    if not ok:
        sys.exit(1)
    if OUT.exists():
        shutil.rmtree(OUT)
    for rel, text in pages.items():
        (OUT / rel).parent.mkdir(parents=True, exist_ok=True)
        (OUT / rel).write_text(text, encoding="utf-8", newline="\n")
    (OUT / "assets").mkdir()
    (OUT / "assets" / "themes.css").write_text(themes.css(), encoding="utf-8", newline="\n")
    for name in ("site.css", "site.js"):
        shutil.copy(WEB / "assets" / name, OUT / "assets" / name)
    shutil.copytree(WEB / "fonts", OUT / "fonts")
    print(f"wrote {len(pages)} pages to {OUT.relative_to(ROOT).as_posix()}/; build IDs: {', '.join(ids)}")
    if args.open:
        webbrowser.open((OUT / "index.html").as_uri())


if __name__ == "__main__":
    main()
